
#' @title create_output
#' @description This function gets the output generated by the model and saves it in a output file.
#' 
#' @param output Vector 
#' @param path The environment of project
#' 
#' @import logging
#'
#' @return
#' 

generarOutput <-  function(resultado, path){
  
  nameOutput <- paste0(path, "output/PredictedNumber.csv")
  
  tryCatch(expr = {
    
    write.csv(resultado, file = nameOutput, 
              row.names = FALSE)
    
  }, error = function(e){
    
    logerror("Saving failed!", logger = 'log')
    stop()
  })
  
}